name: AlphaAwakened
favicon: null
layout_spectrum: 0.9933188767172396
typography_spectrum: 0.62777
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c6296'
    - '#b5c6d1'
    - '#e8edf1'
    - '#769ab5'
    - '#c24548'
  brandStrength: 0.5175722220446914
  lightness: 0.697700276505202
  saturation: 0.08613860444165766
  rhythmicContrast: 0.1551848181989044
purpose: []
